name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout and setup
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup
        uses: actions/setup-node@v7
        with:
          node-version: latest
      - name: Install
        run: npm ci
      - name: Build
        run: npm run prod
        env:
          CI: true
      # Deploy, limited to the master branch
      - name: Deploy
        if: success() && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: d11n.net
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
