name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
    - name: Build
      run: |
        npm run prod
        # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
        touch dist/.nojekyll
        # https://help.github.com/en/articles/managing-a-custom-domain-for-your-github-pages-site
        echo d11n.net > dist/CNAME
      env:
        CI: true
    - name: GitHub Pages Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./dist
        github_token: ${{ secrets.GH_PAT }}
